{
 "title": "Falownik1",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Moc wyjściowa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  Output_active_power_W\nFROM sofar\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Dzisiejsza produkcja",
   "type": "stat",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  Today_production_Wh\nFROM sofar\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Power PV1 PV2",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  PV1_Power_W,\n  PV2_Power_W\nFROM sofar\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Moc w tym tygodniu ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  Output_active_power_W\nFROM sofar\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Prąd PV1 PV2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  PV1_Current_A,\n  PV2_Current_A\nFROM sofar\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Napięcia PV1 PV2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  PV1_Voltage_V\nFROM sofar\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp",
     "schema": [
      { "name": "", "type": "string" }
     ]
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  PV2_Voltage_V\nFROM sofar\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Czestotliwość Sieci",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 35 },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  Grid_frequency_Hz\nFROM sofar\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Napiecie sieci ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  L1_Voltage_V,\n  L2_Voltage_V,\n  L3_Voltage_V\nFROM sofar\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Przewidywania VS rzeczywistość",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  Output_active_power_W\nFROM sofar\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  pv_estimate* 1000 \nFROM solcast\nWHERE\n  $__unixEpochFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  pv_estimate*1000,\n  pv_estimate10*1000,\n  pv_estimate90*1000\nFROM solcast_forecast\nWHERE\n  $__unixEpochFilter(time)\nORDER BY time"
    }
   ]
  }
 ]
}